/*
 * Copyright (C) 2013-2014 High Technology Devices LLC.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _BOARD_MX6Q_JUPITER_H
#define _BOARD_MX6Q_JUPITER_H
#include <mach/iomux-mx6q.h>

static iomux_v3_cfg_t mx6q_jupiter_pads[] = {
	/* UART1 for debug */
	MX6Q_PAD_SD3_DAT7__UART1_TXD,
	MX6Q_PAD_SD3_DAT6__UART1_RXD,
	/* SD1 4 bit */
	MX6Q_PAD_SD1_CLK__USDHC1_CLK,
	MX6Q_PAD_SD1_CMD__USDHC1_CMD,
	MX6Q_PAD_SD1_DAT0__USDHC1_DAT0,
	MX6Q_PAD_SD1_DAT1__USDHC1_DAT1,
	MX6Q_PAD_SD1_DAT2__USDHC1_DAT2,
	MX6Q_PAD_SD1_DAT3__USDHC1_DAT3,
	MX6Q_PAD_KEY_COL1__USDHC1_VSELECT,
	MX6Q_PAD_KEY_ROW2__GPIO_4_11,
	MX6Q_PAD_KEY_ROW1__GPIO_4_9,
	/* SD4 8 bit, high speed mode */
	MX6Q_PAD_NANDF_ALE__USDHC4_RST,
	MX6Q_PAD_SD4_CLK__USDHC4_CLK_200MHZ,
	MX6Q_PAD_SD4_CMD__USDHC4_CMD_200MHZ,
	MX6Q_PAD_SD4_DAT0__USDHC4_DAT0_200MHZ,
	MX6Q_PAD_SD4_DAT1__USDHC4_DAT1_200MHZ,
	MX6Q_PAD_SD4_DAT2__USDHC4_DAT2_200MHZ,
	MX6Q_PAD_SD4_DAT3__USDHC4_DAT3_200MHZ,
	MX6Q_PAD_SD4_DAT4__USDHC4_DAT4_200MHZ,
	MX6Q_PAD_SD4_DAT5__USDHC4_DAT5_200MHZ,
	MX6Q_PAD_SD4_DAT6__USDHC4_DAT6_200MHZ,
	MX6Q_PAD_SD4_DAT7__USDHC4_DAT7_200MHZ,
	/* Ethernet RMII mode */
	MX6Q_PAD_ENET_MDC__ENET_MDC,
	MX6Q_PAD_ENET_MDIO__ENET_MDIO,
	MX6Q_PAD_ENET_RX_ER__ENET_RX_ER,
	MX6Q_PAD_ENET_TX_EN__ENET_TX_EN,
	MX6Q_PAD_ENET_RXD0__ENET_RDATA_0,
	MX6Q_PAD_ENET_RXD1__ENET_RDATA_1,
	MX6Q_PAD_ENET_TXD0__ENET_TDATA_0,
	MX6Q_PAD_ENET_TXD1__ENET_TDATA_1,
	MX6Q_PAD_ENET_CRS_DV__ENET_RX_EN,
	MX6Q_PAD_GPIO_16__ENET_ANATOP_ETHERNET_REF_OUT,
	/* I2C3 */
	MX6Q_PAD_GPIO_6__I2C3_SDA,
	MX6Q_PAD_GPIO_3__I2C3_SCL,
	/* PMIC GPIO interrupt */
	MX6Q_PAD_GPIO_18__GPIO_7_13,
	/* Display control */
	MX6Q_PAD_GPIO_9__PWM1_PWMO,
	MX6Q_PAD_KEY_COL4__GPIO_4_14,
	MX6Q_PAD_KEY_ROW4__GPIO_4_15,
	/* Uart GPS IT530M */
	MX6Q_PAD_EIM_D24__UART3_TXD,
	MX6Q_PAD_EIM_D25__UART3_RXD,
	MX6Q_PAD_EIM_D29__GPIO_3_29,
	/* RS9113 wifi/bt */
	MX6Q_PAD_GPIO_7__GPIO_1_7,
	MX6Q_PAD_SD2_CMD__USDHC2_CMD,
	MX6Q_PAD_SD2_CLK__USDHC2_CLK,
	MX6Q_PAD_SD2_DAT0__USDHC2_DAT0,
	MX6Q_PAD_SD2_DAT1__USDHC2_DAT1,
	MX6Q_PAD_SD2_DAT2__USDHC2_DAT2,
	MX6Q_PAD_SD2_DAT3__USDHC2_DAT3,
	MX6Q_PAD_CSI0_DAT4__AUDMUX_AUD3_TXC,
	MX6Q_PAD_CSI0_DAT5__AUDMUX_AUD3_TXD,
	MX6Q_PAD_CSI0_DAT6__AUDMUX_AUD3_TXFS,
	MX6Q_PAD_CSI0_DAT7__AUDMUX_AUD3_RXD,
	/* USB control pads */
	MX6Q_PAD_GPIO_1__USBOTG_ID,
	MX6Q_PAD_EIM_D16__GPIO_3_16,
	MX6Q_PAD_EIM_D17__GPIO_3_17,
	/* CRTouch interrupt and reset gpio */
	MX6Q_PAD_EIM_D18__GPIO_3_18,
	MX6Q_PAD_GPIO_19__GPIO_4_5,
	MX6Q_PAD_SD3_DAT0__GPIO_7_4,
	/* Android key buttons */
	MX6Q_PAD_EIM_CS0__GPIO_2_23,
	MX6Q_PAD_EIM_CS1__GPIO_2_24,
	MX6Q_PAD_EIM_OE__GPIO_2_25,
};

static iomux_v3_cfg_t mx6q_jupiter_i2c2_pads[] = {
	MX6Q_PAD_KEY_COL3__I2C2_SCL,
	MX6Q_PAD_KEY_ROW3__I2C2_SDA,
};

#endif
